### ISSUE TITLE
Missing code-point-simple.php

### ISSUE THREAD

**Issue by madwort** [ingenerator/code-point-simple#3]
The README says "just run code-point-simple.php" but it's been removed! Maybe you would like to add something like `code-point-simple/src/code-point-simple.php` to get people started? 

`````` <?php
include ('../vendor/autoload.php');

use Ingenerator\CodePointSimple\CodePointSimple;

$codepo = new CodePointSimple;

$codepo->init("../codepo/",'../output/');
$codepo->parse();

?>```
``````

**Comment by acoulton** [comment]
Per #2 we're probably going to abandon this package, but I'd be happy to take that as a PR if you want - I don't think it's been deleted, rather that it was never written/committed. It should probably take and validate the paths from shell arguments.

**Comment by madwort** [comment]
https://github.com/ingenerator/code-point-simple/commit/9fdb75c6c8f982e33f354a53f263ee9b2685d606 classic case of tidying up inadvertently removes functionality... 

`CodePointSimple::parse($argv[1], $argv[2]);`

**Comment by acoulton** [comment]
@madwort ha, good find :) classic case of not having sufficient tests before refactoring...
